adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false

envValueFrom:
  ES_PASSWORD:
    secretKeyRef:
      name: retail-logs-es-elastic-user
      key: elastic

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        uid: mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.monitoring.svc.cluster.local/prometheus
        isDefault: true
        editable: true

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        editable: true

      - name: Elasticsearch Logs
        uid: elasticsearch-logs
        type: elasticsearch
        access: proxy
        url: https://retail-logs-es-http.logging.svc:9200
        database: "[fluentbit-]YYYY.MM.DD"
        basicAuth: true
        basicAuthUser: elastic
        editable: true
        jsonData:
          esVersion: "8.0.0"
          timeField: "@timestamp"
          interval: Daily
          tlsSkipVerify: true
          logMessageField: message
          logLevelField: level
        secureJsonData:
          basicAuthPassword: $__env{ES_PASSWORD}

image:
  registry: 454143665149.dkr.ecr.ap-south-1.amazonaws.com
  repository: observability/grafana
  tag: latest
  pullPolicy: IfNotPresent

sidecar:
  image:
    registry: 454143665149.dkr.ecr.ap-south-1.amazonaws.com
    repository: observability/k8s-sidecar
    tag: 1.30.10
    sha: ""

  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: monitoring
    folder: /tmp/dashboards
    folderAnnotation: grafana_folder
    provider:
      enabled: true
      name: observability
      orgid: 1
      folder: Observability
      type: file
      disableDelete: false
      allowUiUpdates: true
      foldersFromFilesStructure: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi