image:
  registry: 454143665149.dkr.ecr.ap-south-1.amazonaws.com
  repository: observability/alloy
  tag: latest
  pullPolicy: IfNotPresent

controller:
  type: daemonset

serviceAccount:
  create: true
  name: alloy

rbac:
  create: true

alloy:
  configMap:
    create: true
    content: |-
      prometheus.remote_write "mimir" {
        endpoint {
          url = "http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push"
        }
      }

      prometheus.scrape "kube_state_metrics" {
        targets = [{
          __address__ = "kube-state-metrics.monitoring.svc.cluster.local:8080",
          job = "kube-state-metrics",
        }]
        forward_to = [prometheus.remote_write.mimir.receiver]
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }
      discovery.relabel "kubelet" {
        targets = discovery.kubernetes.nodes.targets

        rule {
          target_label = "__address__"
          replacement  = "kubernetes.default.svc.cluster.local:443"
        }

        rule {
          source_labels = ["__meta_kubernetes_node_name"]
          regex         = "(.+)"
          target_label  = "__metrics_path__"
          replacement   = "/api/v1/nodes/${1}/proxy/metrics"
        }

        rule {
          source_labels = ["__meta_kubernetes_node_name"]
          target_label  = "node"
        }

        rule {
          target_label = "job"
          replacement  = "kubelet"
        }
      }

      prometheus.scrape "kubelet" {
        targets           = discovery.relabel.kubelet.output
        scheme            = "https"
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        scrape_interval   = "30s"

        tls_config {
          insecure_skip_verify = true
        }

        forward_to = [prometheus.remote_write.mimir.receiver]
      }

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 512Mi